### ISSUE TITLE
CPS Mismatches

### ISSUE THREAD

**Issue by RobiNino** [cloudbees/groovy-cps#100]
Hello,

Following the introduction of a new warning log message in version 2.7.1 of the Pipeline:Groovy plugin, we are now receiving types of the following warning in builds using the Artifactory Plugin:
`expected to call org.jfrog.hudson.pipeline.common.types.ArtifactoryServer.upload but wound up catching artifactoryUpload`

The pipeline API supported by the Artifactory plugin creates objects, on which methods can be invoked.
For example:
```
def server = Artifactory.server 'my-server'
server.upload ...
```

Notice that the 'server' object allows executing the 'artifactoryUpload' step.
This OOP style is very convenient and allows reusing code and configuration. This approach received very positive feedbacks since it was introduced.
Currently however, this is achieved by having the 'server' instance store the CpsScript, so that it can be used to invoke the step (by using ‘cpsScript.invokeMethod').

The Artifactory pipeline API is available for a few years already and has become extremely popular.
We would appreciate your advice on how to change the plugin in a way that will both satisfy the CPS guidelines without breaking its current functionality and structure.

Thank you

**Comment by dwnusbaum** [comment]
@RobiNino I would close this and instead open an issue on the [Jenkins issue tracker](https://issues.jenkins-ci.org/secure/Dashboard.jspa) with the component set to workflow-cps. At a glance this looks a bit similar to [JENKINS-58407](https://issues.jenkins-ci.org/browse/JENKINS-58407) (though note in that case the user's environment caused the warning to be an exception so most discussion is unrelated to the actual problem), but with an async `Step` rather than a CPS-transformed `Closure`.

**Comment by RobiNino** [comment]
@dwnusbaum Thanks for your reply.
I will go a head and open an issue on the tracker.
Looking at the PR, I saw the mismatch exception that was offered required that `expectedReceiver instanceof MetaClass`, and I guess that will not work for our case of CpsScript. Do you think maybe the option of CpsScript class could be added to the exception?

**Comment by dwnusbaum** [comment]
Addressed downstream in workflow-cps, see [JENKINS-58643](https://issues.jenkins-ci.org/browse/JENKINS-58643) for details.
