### ISSUE TITLE
Incorrect return value from `vars` step

### ISSUE THREAD

**Issue by chrylis** [cloudbees/groovy-cps#89]
I have a custom step, listed in its entirety below. The return value is explicitly specified as `boolean`, and I'm returning a boolean expression, but CPS turns the return into an `Integer` (0/1), which then causes failures downstream (since the sandbox won't coerce back to a boolean).

```
@NonCPS
boolean call(String remote = UPSTREAM_REMOTE, String branch = UPSTREAM_BRANCH) {
  def retVal = sh returnStatus: true, script: "git merge-base --is-ancestor HEAD $remote/$branch"
  return (retVal == 0)
}
```

**Comment by dwnusbaum** [comment]
The problem here is that `sh` is an asynchronous Pipeline step, which means it is always CPS transformed, so you may not call it inside of a method annotated with `@NonCPS`. You may see a warning in your build logs when you do something like this in recent versions of Pipeline: Groovy Plugin that links to [this page](https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches). See [this section](https://wiki.jenkins.io/display/JENKINS/Pipeline+CPS+method+mismatches#PipelineCPSmethodmismatches-UseofPipelinestepsfrom@NonCPS) in particular.

The actual result at runtime is that the return value of the `sh` step becomes the return value of the method. I think that in your case, the fix is just to remove the `@NonCPS` annotation from `call`.
